name = "rolldorado-login-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-login.com.gr"
HMAC_KEY = "2cdc47bc0a13ed9b27a17168e22c8161ad2c1c2ca9ab61512da79c65ebbd1773"
COOKIE_NAME = "8sa"
PLAY_PATH = "start"
BUTTON_ID = "pff2eb054fc71bf07f02fc9acbbce6bed"
GATE_SALT = "fc955f25b2fd04a5"
