name = "rolldorado-login-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-login.com.gr"
HMAC_KEY = "2cdc47bc0a13ed9b27a17168e22c8161ad2c1c2ca9ab61512da79c65ebbd1773"
COOKIE_NAME = "94h"
PLAY_PATH = "go"
BUTTON_ID = "pff2eb054fc71bf07f02fc9acbbce6bed"
GATE_SALT = "6db5d702a262184e"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "35kv"
CTA_SELECTOR = ".play-button"
